# Generated by Django 3.1 on 2020-09-08 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200908_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_list',
            name='auction_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_owner', to=settings.AUTH_USER_MODEL, verbose_name='Auction Owner'),
        ),
    ]
