# Generated by Django 3.1 on 2020-09-10 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_list_auction_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlists',
            name='watchlist_item',
        ),
    ]
