# Generated by Django 3.1 on 2020-09-17 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_watchlists_watchlist_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_bid',
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_bid', to='auctions.auction_list', verbose_name='Auction'),
        ),
    ]
