# Generated by Django 3.1.3 on 2021-01-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200917_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Comment Date'),
        ),
    ]
