# Generated by Django 3.1.3 on 2021-06-16 06:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('ClassID', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Class ID')),
            ],
            options={
                'verbose_name': 'Class Info',
                'verbose_name_plural': 'Class Info',
            },
        ),
        migrations.CreateModel(
            name='SingleChoice',
            fields=[
                ('SingleChoiceIndex', models.AutoField(primary_key=True, serialize=False, verbose_name='Single Choice Index')),
                ('SingleChoiceMark', models.PositiveSmallIntegerField(blank=True, default=5, null=True, verbose_name='Single Choice Mark')),
                ('SingleChoiceContent', models.TextField(verbose_name='Single Choice Content')),
                ('SingleChoiceCategory', models.CharField(max_length=200, verbose_name='Single Choice Category')),
            ],
            options={
                'verbose_name': 'Single Choice',
                'verbose_name_plural': 'Single Choice',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Student ID')),
                ('StudentName', models.CharField(max_length=20, verbose_name='Name')),
                ('StudentGender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6, verbose_name='Gender')),
                ('StudentDepartment', models.CharField(choices=[('CS', 'Computer Science'), ('AM', 'Applied Mathematics'), ('AS', 'Asian Studies'), ('MS', 'Military Science'), ('LJ', 'Law and Justice'), ('IT', 'Information Technology'), ('GD', 'Graphic Design')], default=None, max_length=20, verbose_name='Department')),
                ('StudentEmail', models.EmailField(default=None, max_length=254, verbose_name='Email')),
                ('StudentPassword', models.CharField(default='123456', max_length=15, verbose_name='Password')),
                ('StudentBirthday', models.DateField(verbose_name='Birthday')),
                ('StudentClass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinetest.classinfo', verbose_name='Class ID')),
            ],
            options={
                'verbose_name': 'Student Info',
                'verbose_name_plural': 'Student Info',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('SubjectCode', models.CharField(default='', max_length=200, verbose_name='Subject Code')),
                ('SubjectName', models.CharField(default='', max_length=200, verbose_name='Subject Name')),
                ('SubjectID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Subject ID')),
                ('SubjectLogo', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Subject Logo')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TeacherID', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Teacher ID')),
                ('TeacherName', models.CharField(max_length=20, verbose_name='Name')),
                ('TeacherGender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6, verbose_name='Gender')),
                ('TeacherDepartment', models.CharField(choices=[('CS', 'Computer Science'), ('AM', 'Applied Mathematics'), ('AS', 'Asian Studies'), ('MS', 'Military Science'), ('LJ', 'Law and Justice'), ('IT', 'Information Technology'), ('GD', 'Graphic Design')], default=None, max_length=20, verbose_name='Department')),
                ('TeacherEmail', models.EmailField(default=None, max_length=254, verbose_name='Email')),
                ('TeacherPassword', models.CharField(default='123456', max_length=15, verbose_name='Password')),
                ('TeacherBirthday', models.DateField(verbose_name='Birthday')),
                ('TeacherClass', models.ManyToManyField(blank=True, to='onlinetest.ClassInfo', verbose_name='Class ID')),
                ('TeacherSubject', models.ManyToManyField(blank=True, to='onlinetest.Subject', verbose_name='Teacher Subject')),
            ],
            options={
                'verbose_name': 'Teacher Info',
                'verbose_name_plural': 'Teacher Info',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('TestName', models.CharField(max_length=200, verbose_name='Test Name')),
                ('TestDescription', models.TextField()),
                ('TestID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Test ID')),
                ('TestDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Test date')),
                ('TestTimeLimit', models.PositiveSmallIntegerField(blank=True, default=60, null=True)),
                ('TestClass', models.ManyToManyField(blank=True, to='onlinetest.ClassInfo', verbose_name='Test Class')),
                ('TestCreator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinetest.teacher', verbose_name='Test Creator')),
                ('TestSingleChoiceQues', models.ManyToManyField(blank=True, to='onlinetest.SingleChoice', verbose_name='Test Single Choice Questions')),
                ('TestSubject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinetest.subject', verbose_name='Test Subject')),
            ],
            options={
                'verbose_name': 'Test Info',
                'verbose_name_plural': 'Test Info',
            },
        ),
        migrations.CreateModel(
            name='StudentGrades',
            fields=[
                ('GradeID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Grade ID')),
                ('Grade', models.FloatField(default=-1, verbose_name='Grades')),
                ('DoneState', models.CharField(choices=[('FINISHED', 'FINISHED'), ('UNFINISHED', 'UNFINISHED')], default='UNFINISHED', max_length=20, verbose_name='Done State')),
                ('GradeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('StudentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinetest.student', verbose_name='Student ID')),
                ('Subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlinetest.subject', verbose_name='Subject')),
                ('TestID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlinetest.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Student Grades',
                'verbose_name_plural': 'Student Grades',
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('Answer', models.CharField(max_length=4, verbose_name='Student Answer')),
                ('AnswerID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Answer ID')),
                ('Grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlinetest.studentgrades', verbose_name='Student Grade')),
                ('SingleChoiceQues', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlinetest.singlechoice', verbose_name='Single Choice Question')),
                ('StudentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinetest.student', verbose_name='Student ID')),
                ('TestID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlinetest.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Student Answers',
                'verbose_name_plural': 'Student Answers',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='StudentTest',
            field=models.ManyToManyField(blank=True, to='onlinetest.Test', verbose_name='Test'),
        ),
        migrations.CreateModel(
            name='SingleChoiceImage',
            fields=[
                ('SingleChoiceImageID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Image ID')),
                ('SingleChoiceImageName', models.TextField(verbose_name='Image Description')),
                ('SingleChoiceImage', models.ImageField(upload_to='uploads/', verbose_name='Image')),
                ('SingleChoiceQues', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlinetest.singlechoice', verbose_name='Single Choice Question')),
            ],
            options={
                'verbose_name': 'Single Choice Image',
                'verbose_name_plural': 'Single Choice Image',
            },
        ),
        migrations.CreateModel(
            name='SingleChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SingleChoiceAnswerA', models.CharField(default='aaa', max_length=200, verbose_name='A')),
                ('SingleChoiceAnswerB', models.CharField(default='bbb', max_length=200, verbose_name='B')),
                ('SingleChoiceAnswerC', models.CharField(default='ccc', max_length=200, verbose_name='C')),
                ('SingleChoiceAnswerD', models.CharField(default='ddd', max_length=200, verbose_name='D')),
                ('SingleChoiceCorrect', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default=None, max_length=20, verbose_name='Single Choice True Answer')),
                ('SingleChoiceExplanation', models.TextField(default='Explanation of B: XXXXX;Explanation of B: XXXXX;Explanation of C: XXXXX;Explanation of D: XXXXX;', verbose_name='Explanation')),
                ('SingleChoiceID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinetest.singlechoice', verbose_name='Single Choice ID')),
            ],
            options={
                'verbose_name': 'Single Choice Answer',
                'verbose_name_plural': 'Single Choice Answer',
            },
        ),
        migrations.AddField(
            model_name='singlechoice',
            name='SingleChoiceSubject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinetest.subject', verbose_name='Single Choice Subject'),
        ),
    ]
