# Generated by Django 3.1.3 on 2021-06-17 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlechoiceanswer',
            name='SingleChoiceExplanation',
            field=models.TextField(default='Explanation of A: XXXXX; Explanation of B: XXXXX; Explanation of C: XXXXX; Explanation of D: XXXXX;', verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='test',
            name='TestCreator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlinetest.teacher', verbose_name='Test Creator'),
        ),
        migrations.AlterField(
            model_name='test',
            name='TestSubject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlinetest.subject', verbose_name='Test Subject'),
        ),
    ]
