# Generated by Django 3.1.3 on 2021-06-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0002_auto_20210617_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='TestCreator',
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='DoneState',
            field=models.CharField(choices=[('UNFINISHED', 'UNFINISHED'), ('FINISHED', 'FINISHED')], default='UNFINISHED', max_length=20, verbose_name='Done State'),
        ),
    ]
