# Generated by Django 3.1 on 2020-10-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20201021_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post_like',
            field=models.CharField(choices=[('1', 'None'), ('2', 'Like')], default='1', max_length=50, verbose_name='Post Like'),
        ),
    ]
