# Generated by Django 3.1 on 2020-11-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20201030_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post_like',
            field=models.BooleanField(default=False),
        ),
    ]
